---
title: "Spearman correlations"
output: html_notebook
author: Zakhar Krekhno
---

```{r, echo=FALSE, include=FALSE}
library(phyloseq)
library(readxl)
library(reshape2)
library(psych)
library(tidyverse)
theme_set(theme_classic(base_size = 14))
calc_relative_abund <- function(x) x/sum(x)
```

Import all the necessary matrices for analysis
```{r import}
files <- list.files(path = here::here("corr_mats/"))
otu_file_list <- str_subset(files,"otu")
ms_file_list <- str_subset(files, "ms")
#Import otu counts
otu_list <- map(otu_file_list, 
                    ~read_csv(file = here::here(str_c("corr_mats/",.))))
otu_mat_list <- otu_list %>% 
  map(column_to_rownames, var = "...1") %>% 
  map(as.matrix)
#Import MS data
mq_mat <- read_csv(file = here::here(str_c("corr_mats/",ms_file_list))) %>% 
  column_to_rownames(var = "...1") %>% 
  as.matrix()
```
Continue on to basic Spearman correlations on the whole dataset

```{r spearman, warning=FALSE}
spear_BH <- corr.test(x = mq_mat, y = otu_mat_list [[1]], use = "pairwise", method="spearman", adjust="BH", ci=FALSE)
spear_BH_list <- map(otu_mat_list,
                     ~corr.test(x = mq_mat, y = ., use = "pairwise", method="spearman", adjust="BH", ci=FALSE))
coef_list <- map2(rep(spear_BH_list,each=3),rep(c("r","p","p.adj"),times = 3), ~melt(.x [.y]))
df_list <- map(list(coef_list [1:3],coef_list [4:6],coef_list [7:9]),
               ~reduce(.,left_join, by = c("Var1","Var2")))
walk2(df_list, c("Family","Genus", "Species"),
      ~write_csv(.x,here::here(str_c("spear_results/whole_cohort_",.y,"_cor.csv"))))
d <- df_list [[1]]
```

Plot results of the correlation test
```{r spearman-plot}
df_filt <- df %>% 
  filter(abs(value.x) > 0.3, value.y < 0.05)
ggplot(df_filt, aes(x=Var1, y=Var2)) +
  geom_point(aes(color = value.x, fill = value.x, size = value.y), alpha = 0.6, shape = 21) +
  scale_fill_distiller(palette = "PuOr") +
  scale_color_distiller(palette = "PuOr") +
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 0.9))
```


