---
title: "Spearman correlations for subsets of cohorts"
output: html_notebook
author: Zakhar Krekhno
---

```{r, echo=FALSE, include=FALSE}
library(phyloseq)
library(readxl)
library(reshape2)
library(psych)
library(tidyverse)
theme_set(theme_classic(base_size = 14))
```

Import all the necessary matrices for analysis
```{r import}
files <- list.files(path = here::here("corr_mats/"))
otu_file_list <- str_subset(files,"clr(.)+otu")
tax_file_list <- str_subset(files,"tax")
ms_file_list <- str_subset(files, "ms")
#Import otu counts
otu_list <- map(otu_file_list, 
                    ~read_csv(file = here::here(str_c("corr_mats/",.))))
otu_mat_list <- otu_list %>% 
  map(column_to_rownames, var = "...1") %>% 
  map(as.matrix)
#Import MS data
mq_mat <- read_csv(file = here::here(str_c("corr_mats/",ms_file_list))) %>% 
  column_to_rownames(var = "...1") %>% 
  as.matrix()
```
Import the metadata and create sub-divided matrices.
We will be doing correlations within just Ileum or Colon and within noIBD, active, or inactive IBD
```{r import-meta}
meta_full <- read_excel(here::here("Metadata.xlsx")) %>% 
  select("sample" = `#SampleID`, "group" = Group, everything()) %>% 
  mutate(sample = str_remove(sample, "Rep")) %>% 
  filter(sample %in% rownames(mq_mat)) %>% 
  mutate(across(matches("(Active)|(TI_resection)|(Cholestyramine)"), ~as.character(fct_recode(as_factor(.x), 
                                                Yes = "1", No = "0", Not_applicable = "NA"))))
#Prepare metadata tables
meta_list_starter <- map(vector(mode = "list", length = 6), ~ meta_full)
meta_list <-meta_list_starter %>% 
  map2(rep(c("Colon","Ileum"), each = 3), 
       ~filter(.x, Tissue_type == .y)) %>% 
  map2(rep(c("Not_applicable","No","Yes"),times = 2), 
       ~filter(.x, Active_IBD == .y))
#Name the list for convenience
subgroups <- str_c(rep(c("Colon","Ileum"), each = 3),rep(c("Not_applicable","No","Yes"),times = 2), sep = "_")
names(meta_list) <- subgroups
```

Make appropriate matrices for each group
```{r subset_mq}
mq_list <- map(vector(mode = "list", length = 6*3), ~ mq_mat) %>% 
  map2(rep(meta_list, each=3), ~ .x [rownames(.x) %in% pull(.y,var = sample),])
otu_filt_list <- rep(otu_mat_list, times = 6) %>% 
  map2(rep(meta_list, each=3), ~ .x [rownames(.x) %in% pull(.y,var = sample),])
```


```{r spearman, warning=FALSE}
spear_BH_list <- map(otu_mat_list,
                     ~corr.test(x = mq_mat, y = ., use = "pairwise", method="spearman", adjust="BH", ci=FALSE))
coef_list <- map2(rep(spear_BH_list,each=3),rep(c("r","p","p.adj"),times = 3), ~melt(.x [.y]))
df_list <- map(list(coef_list [1:3],coef_list [4:6],coef_list [7:9]),
               ~reduce(.,left_join, by = c("Var1","Var2")))
#walk2(df_list, c("Family","Genus", "Species"),
 #     ~write_csv(.x,here::here(str_c("spear_results/whole_cohort_clr",.y,"_cor.csv"))))
```

Plot results of the correlation test
```{r spearman-plot}
#Filter the results to only include somewhat meaningful work
df_filt_list <- df_list %>% 
  map(~filter(.,abs(value.x) > 0.3, value.y < 0.05, value < 0.1))
#Get taxonomy to assign meaningul names
tax_list <- map(tax_file_list, 
                    ~read_csv(file = here::here(str_c("corr_mats/",.))))
#Add taxonomy information to each result
df_tax_list <- map2(df_filt_list, tax_list,left_join, by = c("Var2" = "...1"))
ranks <- c("Family","Genus", "Species")
#pdf(here::here("spear_results/Whole cohort Spearman correlations clr-16S.pdf"), height = 12, width = 15)
walk2(df_tax_list,ranks,
      ~print(ggplot(.x, aes_(x=quote(Var1), y=as.name(.y))) +
              geom_point(aes(color = value.x, fill = value.x, size = value), alpha = 0.6, shape = 21) +
              scale_fill_distiller(name = "Spearman rho",palette = "PuOr") +
              scale_color_distiller(name = "Spearman rho", palette = "PuOr") +
              scale_size(name = "Adjusted p",trans = 'reverse') +
              labs(x=element_blank(), title = "Whole cohort Spearman correlations") +
              theme_bw(base_size = 7) + theme(axis.text.x = element_text(angle = 45, hjust = 0.9))))
#dev.off()
#walk2(df_filt_list, c("Family","Genus", "Species"),
 #     ~write_csv(.x,here::here(str_c("spear_results/whole_cohort_clr_filtered",.y,"_cor.csv"))))

```
